// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module add_round_key_block_189 (
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        p_read16,
        p_read17,
        p_read18,
        p_read19,
        p_read20,
        p_read21,
        p_read22,
        p_read23,
        p_read24,
        p_read25,
        p_read26,
        p_read27,
        p_read28,
        p_read29,
        p_read30,
        p_read31,
        p_read32,
        p_read33,
        p_read34,
        p_read35,
        p_read36,
        p_read37,
        p_read38,
        p_read39,
        p_read40,
        p_read41,
        p_read42,
        p_read43,
        p_read44,
        p_read45,
        p_read46,
        p_read47,
        p_read48,
        p_read49,
        p_read50,
        p_read51,
        p_read52,
        p_read53,
        p_read54,
        p_read55,
        p_read56,
        p_read57,
        p_read58,
        p_read59,
        p_read60,
        p_read61,
        p_read62,
        p_read63,
        sub_key_V_6,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        ap_return_25,
        ap_return_26,
        ap_return_27,
        ap_return_28,
        ap_return_29,
        ap_return_30,
        ap_return_31,
        ap_return_32,
        ap_return_33,
        ap_return_34,
        ap_return_35,
        ap_return_36,
        ap_return_37,
        ap_return_38,
        ap_return_39,
        ap_return_40,
        ap_return_41,
        ap_return_42,
        ap_return_43,
        ap_return_44,
        ap_return_45,
        ap_return_46,
        ap_return_47,
        ap_return_48,
        ap_return_49,
        ap_return_50,
        ap_return_51,
        ap_return_52,
        ap_return_53,
        ap_return_54,
        ap_return_55,
        ap_return_56,
        ap_return_57,
        ap_return_58,
        ap_return_59,
        ap_return_60,
        ap_return_61,
        ap_return_62,
        ap_return_63
);


output   ap_ready;
input  [7:0] p_read;
input  [7:0] p_read1;
input  [7:0] p_read2;
input  [7:0] p_read3;
input  [7:0] p_read4;
input  [7:0] p_read5;
input  [7:0] p_read6;
input  [7:0] p_read7;
input  [7:0] p_read8;
input  [7:0] p_read9;
input  [7:0] p_read10;
input  [7:0] p_read11;
input  [7:0] p_read12;
input  [7:0] p_read13;
input  [7:0] p_read14;
input  [7:0] p_read15;
input  [7:0] p_read16;
input  [7:0] p_read17;
input  [7:0] p_read18;
input  [7:0] p_read19;
input  [7:0] p_read20;
input  [7:0] p_read21;
input  [7:0] p_read22;
input  [7:0] p_read23;
input  [7:0] p_read24;
input  [7:0] p_read25;
input  [7:0] p_read26;
input  [7:0] p_read27;
input  [7:0] p_read28;
input  [7:0] p_read29;
input  [7:0] p_read30;
input  [7:0] p_read31;
input  [7:0] p_read32;
input  [7:0] p_read33;
input  [7:0] p_read34;
input  [7:0] p_read35;
input  [7:0] p_read36;
input  [7:0] p_read37;
input  [7:0] p_read38;
input  [7:0] p_read39;
input  [7:0] p_read40;
input  [7:0] p_read41;
input  [7:0] p_read42;
input  [7:0] p_read43;
input  [7:0] p_read44;
input  [7:0] p_read45;
input  [7:0] p_read46;
input  [7:0] p_read47;
input  [7:0] p_read48;
input  [7:0] p_read49;
input  [7:0] p_read50;
input  [7:0] p_read51;
input  [7:0] p_read52;
input  [7:0] p_read53;
input  [7:0] p_read54;
input  [7:0] p_read55;
input  [7:0] p_read56;
input  [7:0] p_read57;
input  [7:0] p_read58;
input  [7:0] p_read59;
input  [7:0] p_read60;
input  [7:0] p_read61;
input  [7:0] p_read62;
input  [7:0] p_read63;
input  [127:0] sub_key_V_6;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;
output  [7:0] ap_return_2;
output  [7:0] ap_return_3;
output  [7:0] ap_return_4;
output  [7:0] ap_return_5;
output  [7:0] ap_return_6;
output  [7:0] ap_return_7;
output  [7:0] ap_return_8;
output  [7:0] ap_return_9;
output  [7:0] ap_return_10;
output  [7:0] ap_return_11;
output  [7:0] ap_return_12;
output  [7:0] ap_return_13;
output  [7:0] ap_return_14;
output  [7:0] ap_return_15;
output  [7:0] ap_return_16;
output  [7:0] ap_return_17;
output  [7:0] ap_return_18;
output  [7:0] ap_return_19;
output  [7:0] ap_return_20;
output  [7:0] ap_return_21;
output  [7:0] ap_return_22;
output  [7:0] ap_return_23;
output  [7:0] ap_return_24;
output  [7:0] ap_return_25;
output  [7:0] ap_return_26;
output  [7:0] ap_return_27;
output  [7:0] ap_return_28;
output  [7:0] ap_return_29;
output  [7:0] ap_return_30;
output  [7:0] ap_return_31;
output  [7:0] ap_return_32;
output  [7:0] ap_return_33;
output  [7:0] ap_return_34;
output  [7:0] ap_return_35;
output  [7:0] ap_return_36;
output  [7:0] ap_return_37;
output  [7:0] ap_return_38;
output  [7:0] ap_return_39;
output  [7:0] ap_return_40;
output  [7:0] ap_return_41;
output  [7:0] ap_return_42;
output  [7:0] ap_return_43;
output  [7:0] ap_return_44;
output  [7:0] ap_return_45;
output  [7:0] ap_return_46;
output  [7:0] ap_return_47;
output  [7:0] ap_return_48;
output  [7:0] ap_return_49;
output  [7:0] ap_return_50;
output  [7:0] ap_return_51;
output  [7:0] ap_return_52;
output  [7:0] ap_return_53;
output  [7:0] ap_return_54;
output  [7:0] ap_return_55;
output  [7:0] ap_return_56;
output  [7:0] ap_return_57;
output  [7:0] ap_return_58;
output  [7:0] ap_return_59;
output  [7:0] ap_return_60;
output  [7:0] ap_return_61;
output  [7:0] ap_return_62;
output  [7:0] ap_return_63;

wire   [7:0] p_Result_s_fu_588_p4;
wire   [7:0] p_Result_0_1_fu_622_p4;
wire   [7:0] p_Result_0_2_fu_656_p4;
wire   [7:0] p_Result_0_3_fu_690_p4;
wire   [7:0] p_Result_1_fu_724_p4;
wire   [7:0] p_Result_1_1_fu_758_p4;
wire   [7:0] p_Result_1_2_fu_792_p4;
wire   [7:0] p_Result_1_3_fu_826_p4;
wire   [7:0] p_Result_2_fu_860_p4;
wire   [7:0] p_Result_2_1_fu_894_p4;
wire   [7:0] p_Result_2_2_fu_928_p4;
wire   [7:0] p_Result_2_3_fu_962_p4;
wire   [7:0] p_Result_3_fu_996_p4;
wire   [7:0] p_Result_3_1_fu_1030_p4;
wire   [7:0] p_Result_3_2_fu_1064_p4;
wire   [7:0] tmp_fu_1098_p1;
wire   [7:0] p_s_fu_598_p2;
wire   [7:0] p_0_1_fu_632_p2;
wire   [7:0] p_0_2_fu_666_p2;
wire   [7:0] p_0_3_fu_700_p2;
wire   [7:0] p_1_fu_734_p2;
wire   [7:0] p_1_1_fu_768_p2;
wire   [7:0] p_1_2_fu_802_p2;
wire   [7:0] p_1_3_fu_836_p2;
wire   [7:0] p_2_fu_870_p2;
wire   [7:0] p_2_1_fu_904_p2;
wire   [7:0] p_2_2_fu_938_p2;
wire   [7:0] p_2_3_fu_972_p2;
wire   [7:0] p_3_fu_1006_p2;
wire   [7:0] p_3_1_fu_1040_p2;
wire   [7:0] p_3_2_fu_1074_p2;
wire   [7:0] p_3_3_fu_1102_p2;
wire   [7:0] p_0_0_1_fu_604_p2;
wire   [7:0] p_0_1_1_fu_638_p2;
wire   [7:0] p_0_2_1_fu_672_p2;
wire   [7:0] p_0_3_1_fu_706_p2;
wire   [7:0] p_1_0_1_fu_740_p2;
wire   [7:0] p_1_1_1_fu_774_p2;
wire   [7:0] p_1_2_1_fu_808_p2;
wire   [7:0] p_1_3_1_fu_842_p2;
wire   [7:0] p_2_0_1_fu_876_p2;
wire   [7:0] p_2_1_1_fu_910_p2;
wire   [7:0] p_2_2_1_fu_944_p2;
wire   [7:0] p_2_3_1_fu_978_p2;
wire   [7:0] p_3_0_1_fu_1012_p2;
wire   [7:0] p_3_1_1_fu_1046_p2;
wire   [7:0] p_3_2_1_fu_1080_p2;
wire   [7:0] p_3_3_1_fu_1108_p2;
wire   [7:0] p_0_0_2_fu_610_p2;
wire   [7:0] p_0_1_2_fu_644_p2;
wire   [7:0] p_0_2_2_fu_678_p2;
wire   [7:0] p_0_3_2_fu_712_p2;
wire   [7:0] p_1_0_2_fu_746_p2;
wire   [7:0] p_1_1_2_fu_780_p2;
wire   [7:0] p_1_2_2_fu_814_p2;
wire   [7:0] p_1_3_2_fu_848_p2;
wire   [7:0] p_2_0_2_fu_882_p2;
wire   [7:0] p_2_1_2_fu_916_p2;
wire   [7:0] p_2_2_2_fu_950_p2;
wire   [7:0] p_2_3_2_fu_984_p2;
wire   [7:0] p_3_0_2_fu_1018_p2;
wire   [7:0] p_3_1_2_fu_1052_p2;
wire   [7:0] p_3_2_2_fu_1086_p2;
wire   [7:0] p_3_3_2_fu_1114_p2;
wire   [7:0] p_0_0_3_fu_616_p2;
wire   [7:0] p_0_1_3_fu_650_p2;
wire   [7:0] p_0_2_3_fu_684_p2;
wire   [7:0] p_0_3_3_fu_718_p2;
wire   [7:0] p_1_0_3_fu_752_p2;
wire   [7:0] p_1_1_3_fu_786_p2;
wire   [7:0] p_1_2_3_fu_820_p2;
wire   [7:0] p_1_3_3_fu_854_p2;
wire   [7:0] p_2_0_3_fu_888_p2;
wire   [7:0] p_2_1_3_fu_922_p2;
wire   [7:0] p_2_2_3_fu_956_p2;
wire   [7:0] p_2_3_3_fu_990_p2;
wire   [7:0] p_3_0_3_fu_1024_p2;
wire   [7:0] p_3_1_3_fu_1058_p2;
wire   [7:0] p_3_2_3_fu_1092_p2;
wire   [7:0] p_3_3_3_fu_1120_p2;

assign ap_ready = 1'b1;

assign ap_return_0 = p_s_fu_598_p2;

assign ap_return_1 = p_0_1_fu_632_p2;

assign ap_return_10 = p_2_2_fu_938_p2;

assign ap_return_11 = p_2_3_fu_972_p2;

assign ap_return_12 = p_3_fu_1006_p2;

assign ap_return_13 = p_3_1_fu_1040_p2;

assign ap_return_14 = p_3_2_fu_1074_p2;

assign ap_return_15 = p_3_3_fu_1102_p2;

assign ap_return_16 = p_0_0_1_fu_604_p2;

assign ap_return_17 = p_0_1_1_fu_638_p2;

assign ap_return_18 = p_0_2_1_fu_672_p2;

assign ap_return_19 = p_0_3_1_fu_706_p2;

assign ap_return_2 = p_0_2_fu_666_p2;

assign ap_return_20 = p_1_0_1_fu_740_p2;

assign ap_return_21 = p_1_1_1_fu_774_p2;

assign ap_return_22 = p_1_2_1_fu_808_p2;

assign ap_return_23 = p_1_3_1_fu_842_p2;

assign ap_return_24 = p_2_0_1_fu_876_p2;

assign ap_return_25 = p_2_1_1_fu_910_p2;

assign ap_return_26 = p_2_2_1_fu_944_p2;

assign ap_return_27 = p_2_3_1_fu_978_p2;

assign ap_return_28 = p_3_0_1_fu_1012_p2;

assign ap_return_29 = p_3_1_1_fu_1046_p2;

assign ap_return_3 = p_0_3_fu_700_p2;

assign ap_return_30 = p_3_2_1_fu_1080_p2;

assign ap_return_31 = p_3_3_1_fu_1108_p2;

assign ap_return_32 = p_0_0_2_fu_610_p2;

assign ap_return_33 = p_0_1_2_fu_644_p2;

assign ap_return_34 = p_0_2_2_fu_678_p2;

assign ap_return_35 = p_0_3_2_fu_712_p2;

assign ap_return_36 = p_1_0_2_fu_746_p2;

assign ap_return_37 = p_1_1_2_fu_780_p2;

assign ap_return_38 = p_1_2_2_fu_814_p2;

assign ap_return_39 = p_1_3_2_fu_848_p2;

assign ap_return_4 = p_1_fu_734_p2;

assign ap_return_40 = p_2_0_2_fu_882_p2;

assign ap_return_41 = p_2_1_2_fu_916_p2;

assign ap_return_42 = p_2_2_2_fu_950_p2;

assign ap_return_43 = p_2_3_2_fu_984_p2;

assign ap_return_44 = p_3_0_2_fu_1018_p2;

assign ap_return_45 = p_3_1_2_fu_1052_p2;

assign ap_return_46 = p_3_2_2_fu_1086_p2;

assign ap_return_47 = p_3_3_2_fu_1114_p2;

assign ap_return_48 = p_0_0_3_fu_616_p2;

assign ap_return_49 = p_0_1_3_fu_650_p2;

assign ap_return_5 = p_1_1_fu_768_p2;

assign ap_return_50 = p_0_2_3_fu_684_p2;

assign ap_return_51 = p_0_3_3_fu_718_p2;

assign ap_return_52 = p_1_0_3_fu_752_p2;

assign ap_return_53 = p_1_1_3_fu_786_p2;

assign ap_return_54 = p_1_2_3_fu_820_p2;

assign ap_return_55 = p_1_3_3_fu_854_p2;

assign ap_return_56 = p_2_0_3_fu_888_p2;

assign ap_return_57 = p_2_1_3_fu_922_p2;

assign ap_return_58 = p_2_2_3_fu_956_p2;

assign ap_return_59 = p_2_3_3_fu_990_p2;

assign ap_return_6 = p_1_2_fu_802_p2;

assign ap_return_60 = p_3_0_3_fu_1024_p2;

assign ap_return_61 = p_3_1_3_fu_1058_p2;

assign ap_return_62 = p_3_2_3_fu_1092_p2;

assign ap_return_63 = p_3_3_3_fu_1120_p2;

assign ap_return_7 = p_1_3_fu_836_p2;

assign ap_return_8 = p_2_fu_870_p2;

assign ap_return_9 = p_2_1_fu_904_p2;

assign p_0_0_1_fu_604_p2 = (p_read16 ^ p_Result_s_fu_588_p4);

assign p_0_0_2_fu_610_p2 = (p_read32 ^ p_Result_s_fu_588_p4);

assign p_0_0_3_fu_616_p2 = (p_read48 ^ p_Result_s_fu_588_p4);

assign p_0_1_1_fu_638_p2 = (p_read17 ^ p_Result_0_1_fu_622_p4);

assign p_0_1_2_fu_644_p2 = (p_read33 ^ p_Result_0_1_fu_622_p4);

assign p_0_1_3_fu_650_p2 = (p_read49 ^ p_Result_0_1_fu_622_p4);

assign p_0_1_fu_632_p2 = (p_read1 ^ p_Result_0_1_fu_622_p4);

assign p_0_2_1_fu_672_p2 = (p_read18 ^ p_Result_0_2_fu_656_p4);

assign p_0_2_2_fu_678_p2 = (p_read34 ^ p_Result_0_2_fu_656_p4);

assign p_0_2_3_fu_684_p2 = (p_read50 ^ p_Result_0_2_fu_656_p4);

assign p_0_2_fu_666_p2 = (p_read2 ^ p_Result_0_2_fu_656_p4);

assign p_0_3_1_fu_706_p2 = (p_read19 ^ p_Result_0_3_fu_690_p4);

assign p_0_3_2_fu_712_p2 = (p_read35 ^ p_Result_0_3_fu_690_p4);

assign p_0_3_3_fu_718_p2 = (p_read51 ^ p_Result_0_3_fu_690_p4);

assign p_0_3_fu_700_p2 = (p_read3 ^ p_Result_0_3_fu_690_p4);

assign p_1_0_1_fu_740_p2 = (p_read20 ^ p_Result_1_fu_724_p4);

assign p_1_0_2_fu_746_p2 = (p_read36 ^ p_Result_1_fu_724_p4);

assign p_1_0_3_fu_752_p2 = (p_read52 ^ p_Result_1_fu_724_p4);

assign p_1_1_1_fu_774_p2 = (p_read21 ^ p_Result_1_1_fu_758_p4);

assign p_1_1_2_fu_780_p2 = (p_read37 ^ p_Result_1_1_fu_758_p4);

assign p_1_1_3_fu_786_p2 = (p_read53 ^ p_Result_1_1_fu_758_p4);

assign p_1_1_fu_768_p2 = (p_read5 ^ p_Result_1_1_fu_758_p4);

assign p_1_2_1_fu_808_p2 = (p_read22 ^ p_Result_1_2_fu_792_p4);

assign p_1_2_2_fu_814_p2 = (p_read38 ^ p_Result_1_2_fu_792_p4);

assign p_1_2_3_fu_820_p2 = (p_read54 ^ p_Result_1_2_fu_792_p4);

assign p_1_2_fu_802_p2 = (p_read6 ^ p_Result_1_2_fu_792_p4);

assign p_1_3_1_fu_842_p2 = (p_read23 ^ p_Result_1_3_fu_826_p4);

assign p_1_3_2_fu_848_p2 = (p_read39 ^ p_Result_1_3_fu_826_p4);

assign p_1_3_3_fu_854_p2 = (p_read55 ^ p_Result_1_3_fu_826_p4);

assign p_1_3_fu_836_p2 = (p_read7 ^ p_Result_1_3_fu_826_p4);

assign p_1_fu_734_p2 = (p_read4 ^ p_Result_1_fu_724_p4);

assign p_2_0_1_fu_876_p2 = (p_read24 ^ p_Result_2_fu_860_p4);

assign p_2_0_2_fu_882_p2 = (p_read40 ^ p_Result_2_fu_860_p4);

assign p_2_0_3_fu_888_p2 = (p_read56 ^ p_Result_2_fu_860_p4);

assign p_2_1_1_fu_910_p2 = (p_read25 ^ p_Result_2_1_fu_894_p4);

assign p_2_1_2_fu_916_p2 = (p_read41 ^ p_Result_2_1_fu_894_p4);

assign p_2_1_3_fu_922_p2 = (p_read57 ^ p_Result_2_1_fu_894_p4);

assign p_2_1_fu_904_p2 = (p_read9 ^ p_Result_2_1_fu_894_p4);

assign p_2_2_1_fu_944_p2 = (p_read26 ^ p_Result_2_2_fu_928_p4);

assign p_2_2_2_fu_950_p2 = (p_read42 ^ p_Result_2_2_fu_928_p4);

assign p_2_2_3_fu_956_p2 = (p_read58 ^ p_Result_2_2_fu_928_p4);

assign p_2_2_fu_938_p2 = (p_read10 ^ p_Result_2_2_fu_928_p4);

assign p_2_3_1_fu_978_p2 = (p_read27 ^ p_Result_2_3_fu_962_p4);

assign p_2_3_2_fu_984_p2 = (p_read43 ^ p_Result_2_3_fu_962_p4);

assign p_2_3_3_fu_990_p2 = (p_read59 ^ p_Result_2_3_fu_962_p4);

assign p_2_3_fu_972_p2 = (p_read11 ^ p_Result_2_3_fu_962_p4);

assign p_2_fu_870_p2 = (p_read8 ^ p_Result_2_fu_860_p4);

assign p_3_0_1_fu_1012_p2 = (p_read28 ^ p_Result_3_fu_996_p4);

assign p_3_0_2_fu_1018_p2 = (p_read44 ^ p_Result_3_fu_996_p4);

assign p_3_0_3_fu_1024_p2 = (p_read60 ^ p_Result_3_fu_996_p4);

assign p_3_1_1_fu_1046_p2 = (p_read29 ^ p_Result_3_1_fu_1030_p4);

assign p_3_1_2_fu_1052_p2 = (p_read45 ^ p_Result_3_1_fu_1030_p4);

assign p_3_1_3_fu_1058_p2 = (p_read61 ^ p_Result_3_1_fu_1030_p4);

assign p_3_1_fu_1040_p2 = (p_read13 ^ p_Result_3_1_fu_1030_p4);

assign p_3_2_1_fu_1080_p2 = (p_read30 ^ p_Result_3_2_fu_1064_p4);

assign p_3_2_2_fu_1086_p2 = (p_read46 ^ p_Result_3_2_fu_1064_p4);

assign p_3_2_3_fu_1092_p2 = (p_read62 ^ p_Result_3_2_fu_1064_p4);

assign p_3_2_fu_1074_p2 = (p_read14 ^ p_Result_3_2_fu_1064_p4);

assign p_3_3_1_fu_1108_p2 = (tmp_fu_1098_p1 ^ p_read31);

assign p_3_3_2_fu_1114_p2 = (tmp_fu_1098_p1 ^ p_read47);

assign p_3_3_3_fu_1120_p2 = (tmp_fu_1098_p1 ^ p_read63);

assign p_3_3_fu_1102_p2 = (tmp_fu_1098_p1 ^ p_read15);

assign p_3_fu_1006_p2 = (p_read12 ^ p_Result_3_fu_996_p4);

assign p_Result_0_1_fu_622_p4 = {{sub_key_V_6[95:88]}};

assign p_Result_0_2_fu_656_p4 = {{sub_key_V_6[63:56]}};

assign p_Result_0_3_fu_690_p4 = {{sub_key_V_6[31:24]}};

assign p_Result_1_1_fu_758_p4 = {{sub_key_V_6[87:80]}};

assign p_Result_1_2_fu_792_p4 = {{sub_key_V_6[55:48]}};

assign p_Result_1_3_fu_826_p4 = {{sub_key_V_6[23:16]}};

assign p_Result_1_fu_724_p4 = {{sub_key_V_6[119:112]}};

assign p_Result_2_1_fu_894_p4 = {{sub_key_V_6[79:72]}};

assign p_Result_2_2_fu_928_p4 = {{sub_key_V_6[47:40]}};

assign p_Result_2_3_fu_962_p4 = {{sub_key_V_6[15:8]}};

assign p_Result_2_fu_860_p4 = {{sub_key_V_6[111:104]}};

assign p_Result_3_1_fu_1030_p4 = {{sub_key_V_6[71:64]}};

assign p_Result_3_2_fu_1064_p4 = {{sub_key_V_6[39:32]}};

assign p_Result_3_fu_996_p4 = {{sub_key_V_6[103:96]}};

assign p_Result_s_fu_588_p4 = {{sub_key_V_6[127:120]}};

assign p_s_fu_598_p2 = (p_read ^ p_Result_s_fu_588_p4);

assign tmp_fu_1098_p1 = sub_key_V_6[7:0];

endmodule //add_round_key_block_189
