// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "block_aes_128.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic block_aes_128::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic block_aes_128::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> block_aes_128::ap_ST_fsm_state1 = "1";
const sc_lv<2> block_aes_128::ap_ST_fsm_state2 = "10";
const sc_lv<32> block_aes_128::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> block_aes_128::ap_const_lv32_1 = "1";
const sc_lv<1> block_aes_128::ap_const_lv1_0 = "0";
const sc_lv<1> block_aes_128::ap_const_lv1_1 = "1";
const bool block_aes_128::ap_const_boolean_0 = false;
const bool block_aes_128::ap_const_boolean_1 = true;

block_aes_128::block_aes_128(sc_module_name name) : sc_module(name), mVcdFile(0) {
    sub_key_V_U = new block_aes_128_sub_key_V("sub_key_V_U");
    sub_key_V_U->clk(ap_clk);
    sub_key_V_U->reset(ap_rst);
    sub_key_V_U->address0(sub_key_V_address0);
    sub_key_V_U->ce0(sub_key_V_ce0);
    sub_key_V_U->we0(sub_key_V_we0);
    sub_key_V_U->d0(grp_key_expansion_fu_65_sub_key_V_2_d0);
    sub_key_V_U->q0(sub_key_V_q0);
    grp_proc_block_fu_56 = new proc_block("grp_proc_block_fu_56");
    grp_proc_block_fu_56->ap_clk(ap_clk);
    grp_proc_block_fu_56->ap_rst(ap_rst);
    grp_proc_block_fu_56->ap_start(grp_proc_block_fu_56_ap_start);
    grp_proc_block_fu_56->ap_done(grp_proc_block_fu_56_ap_done);
    grp_proc_block_fu_56->ap_idle(grp_proc_block_fu_56_ap_idle);
    grp_proc_block_fu_56->ap_ready(grp_proc_block_fu_56_ap_ready);
    grp_proc_block_fu_56->in_V(IV_V);
    grp_proc_block_fu_56->sub_key_V_address0(grp_proc_block_fu_56_sub_key_V_address0);
    grp_proc_block_fu_56->sub_key_V_ce0(grp_proc_block_fu_56_sub_key_V_ce0);
    grp_proc_block_fu_56->sub_key_V_q0(sub_key_V_q0);
    grp_proc_block_fu_56->ap_return(grp_proc_block_fu_56_ap_return);
    grp_key_expansion_fu_65 = new key_expansion("grp_key_expansion_fu_65");
    grp_key_expansion_fu_65->ap_clk(ap_clk);
    grp_key_expansion_fu_65->ap_rst(ap_rst);
    grp_key_expansion_fu_65->ap_start(grp_key_expansion_fu_65_ap_start);
    grp_key_expansion_fu_65->ap_done(grp_key_expansion_fu_65_ap_done);
    grp_key_expansion_fu_65->ap_idle(grp_key_expansion_fu_65_ap_idle);
    grp_key_expansion_fu_65->ap_ready(grp_key_expansion_fu_65_ap_ready);
    grp_key_expansion_fu_65->key_V(key_V);
    grp_key_expansion_fu_65->sub_key_V_2_address0(grp_key_expansion_fu_65_sub_key_V_2_address0);
    grp_key_expansion_fu_65->sub_key_V_2_ce0(grp_key_expansion_fu_65_sub_key_V_2_ce0);
    grp_key_expansion_fu_65->sub_key_V_2_we0(grp_key_expansion_fu_65_sub_key_V_2_we0);
    grp_key_expansion_fu_65->sub_key_V_2_d0(grp_key_expansion_fu_65_sub_key_V_2_d0);
    grp_key_expansion_fu_65->sub_key_V_2_q0(sub_key_V_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state2_on_subcall_done);
    sensitive << ( init_read_read_fu_28_p2 );
    sensitive << ( grp_proc_block_fu_56_ap_done );
    sensitive << ( grp_key_expansion_fu_65_ap_done );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_block_state2_on_subcall_done );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_block_state2_on_subcall_done );

    SC_METHOD(thread_ap_return);
    sensitive << ( grp_proc_block_fu_56_ap_return );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_block_state2_on_subcall_done );

    SC_METHOD(thread_grp_key_expansion_fu_65_ap_start);
    sensitive << ( grp_key_expansion_fu_65_ap_start_reg );

    SC_METHOD(thread_grp_proc_block_fu_56_ap_start);
    sensitive << ( grp_proc_block_fu_56_ap_start_reg );

    SC_METHOD(thread_init_read_read_fu_28_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( init );

    SC_METHOD(thread_sub_key_V_address0);
    sensitive << ( init_read_read_fu_28_p2 );
    sensitive << ( grp_proc_block_fu_56_sub_key_V_address0 );
    sensitive << ( grp_key_expansion_fu_65_sub_key_V_2_address0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_sub_key_V_ce0);
    sensitive << ( init_read_read_fu_28_p2 );
    sensitive << ( grp_proc_block_fu_56_sub_key_V_ce0 );
    sensitive << ( grp_key_expansion_fu_65_sub_key_V_2_ce0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_sub_key_V_we0);
    sensitive << ( init_read_read_fu_28_p2 );
    sensitive << ( grp_key_expansion_fu_65_sub_key_V_2_we0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_block_state2_on_subcall_done );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "01";
    grp_proc_block_fu_56_ap_start_reg = SC_LOGIC_0;
    grp_key_expansion_fu_65_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "block_aes_128_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, IV_V, "(port)IV_V");
    sc_trace(mVcdFile, key_V, "(port)key_V");
    sc_trace(mVcdFile, init, "(port)init");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, sub_key_V_address0, "sub_key_V_address0");
    sc_trace(mVcdFile, sub_key_V_ce0, "sub_key_V_ce0");
    sc_trace(mVcdFile, sub_key_V_we0, "sub_key_V_we0");
    sc_trace(mVcdFile, sub_key_V_q0, "sub_key_V_q0");
    sc_trace(mVcdFile, init_read_read_fu_28_p2, "init_read_read_fu_28_p2");
    sc_trace(mVcdFile, grp_proc_block_fu_56_ap_start, "grp_proc_block_fu_56_ap_start");
    sc_trace(mVcdFile, grp_proc_block_fu_56_ap_done, "grp_proc_block_fu_56_ap_done");
    sc_trace(mVcdFile, grp_proc_block_fu_56_ap_idle, "grp_proc_block_fu_56_ap_idle");
    sc_trace(mVcdFile, grp_proc_block_fu_56_ap_ready, "grp_proc_block_fu_56_ap_ready");
    sc_trace(mVcdFile, grp_proc_block_fu_56_sub_key_V_address0, "grp_proc_block_fu_56_sub_key_V_address0");
    sc_trace(mVcdFile, grp_proc_block_fu_56_sub_key_V_ce0, "grp_proc_block_fu_56_sub_key_V_ce0");
    sc_trace(mVcdFile, grp_proc_block_fu_56_ap_return, "grp_proc_block_fu_56_ap_return");
    sc_trace(mVcdFile, grp_key_expansion_fu_65_ap_start, "grp_key_expansion_fu_65_ap_start");
    sc_trace(mVcdFile, grp_key_expansion_fu_65_ap_done, "grp_key_expansion_fu_65_ap_done");
    sc_trace(mVcdFile, grp_key_expansion_fu_65_ap_idle, "grp_key_expansion_fu_65_ap_idle");
    sc_trace(mVcdFile, grp_key_expansion_fu_65_ap_ready, "grp_key_expansion_fu_65_ap_ready");
    sc_trace(mVcdFile, grp_key_expansion_fu_65_sub_key_V_2_address0, "grp_key_expansion_fu_65_sub_key_V_2_address0");
    sc_trace(mVcdFile, grp_key_expansion_fu_65_sub_key_V_2_ce0, "grp_key_expansion_fu_65_sub_key_V_2_ce0");
    sc_trace(mVcdFile, grp_key_expansion_fu_65_sub_key_V_2_we0, "grp_key_expansion_fu_65_sub_key_V_2_we0");
    sc_trace(mVcdFile, grp_key_expansion_fu_65_sub_key_V_2_d0, "grp_key_expansion_fu_65_sub_key_V_2_d0");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, ap_block_state2_on_subcall_done, "ap_block_state2_on_subcall_done");
    sc_trace(mVcdFile, grp_proc_block_fu_56_ap_start_reg, "grp_proc_block_fu_56_ap_start_reg");
    sc_trace(mVcdFile, grp_key_expansion_fu_65_ap_start_reg, "grp_key_expansion_fu_65_ap_start_reg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("block_aes_128.hdltvin.dat");
    mHdltvoutHandle.open("block_aes_128.hdltvout.dat");
}

block_aes_128::~block_aes_128() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete sub_key_V_U;
    delete grp_proc_block_fu_56;
    delete grp_key_expansion_fu_65;
}

void block_aes_128::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_key_expansion_fu_65_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
             esl_seteq<1,1,1>(init_read_read_fu_28_p2.read(), ap_const_lv1_1))) {
            grp_key_expansion_fu_65_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_key_expansion_fu_65_ap_ready.read())) {
            grp_key_expansion_fu_65_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_proc_block_fu_56_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
             esl_seteq<1,1,1>(init_read_read_fu_28_p2.read(), ap_const_lv1_0))) {
            grp_proc_block_fu_56_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_proc_block_fu_56_ap_ready.read())) {
            grp_proc_block_fu_56_ap_start_reg = ap_const_logic_0;
        }
    }
}

void block_aes_128::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void block_aes_128::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void block_aes_128::thread_ap_block_state2_on_subcall_done() {
    ap_block_state2_on_subcall_done = ((esl_seteq<1,1,1>(ap_const_logic_0, grp_proc_block_fu_56_ap_done.read()) && 
  esl_seteq<1,1,1>(init_read_read_fu_28_p2.read(), ap_const_lv1_0)) || (esl_seteq<1,1,1>(ap_const_logic_0, grp_key_expansion_fu_65_ap_done.read()) && 
  esl_seteq<1,1,1>(init_read_read_fu_28_p2.read(), ap_const_lv1_1)));
}

void block_aes_128::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_block_state2_on_subcall_done.read(), ap_const_boolean_0))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void block_aes_128::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void block_aes_128::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_block_state2_on_subcall_done.read(), ap_const_boolean_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void block_aes_128::thread_ap_return() {
    ap_return = grp_proc_block_fu_56_ap_return.read();
}

void block_aes_128::thread_grp_key_expansion_fu_65_ap_start() {
    grp_key_expansion_fu_65_ap_start = grp_key_expansion_fu_65_ap_start_reg.read();
}

void block_aes_128::thread_grp_proc_block_fu_56_ap_start() {
    grp_proc_block_fu_56_ap_start = grp_proc_block_fu_56_ap_start_reg.read();
}

void block_aes_128::thread_init_read_read_fu_28_p2() {
    init_read_read_fu_28_p2 =  (sc_lv<1>) (init.read());
}

void block_aes_128::thread_sub_key_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        if (esl_seteq<1,1,1>(init_read_read_fu_28_p2.read(), ap_const_lv1_1)) {
            sub_key_V_address0 = grp_key_expansion_fu_65_sub_key_V_2_address0.read();
        } else if (esl_seteq<1,1,1>(init_read_read_fu_28_p2.read(), ap_const_lv1_0)) {
            sub_key_V_address0 = grp_proc_block_fu_56_sub_key_V_address0.read();
        } else {
            sub_key_V_address0 = "XXXX";
        }
    } else {
        sub_key_V_address0 = "XXXX";
    }
}

void block_aes_128::thread_sub_key_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        if (esl_seteq<1,1,1>(init_read_read_fu_28_p2.read(), ap_const_lv1_1)) {
            sub_key_V_ce0 = grp_key_expansion_fu_65_sub_key_V_2_ce0.read();
        } else if (esl_seteq<1,1,1>(init_read_read_fu_28_p2.read(), ap_const_lv1_0)) {
            sub_key_V_ce0 = grp_proc_block_fu_56_sub_key_V_ce0.read();
        } else {
            sub_key_V_ce0 = ap_const_logic_0;
        }
    } else {
        sub_key_V_ce0 = ap_const_logic_0;
    }
}

void block_aes_128::thread_sub_key_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(init_read_read_fu_28_p2.read(), ap_const_lv1_1))) {
        sub_key_V_we0 = grp_key_expansion_fu_65_sub_key_V_2_we0.read();
    } else {
        sub_key_V_we0 = ap_const_logic_0;
    }
}

void block_aes_128::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_block_state2_on_subcall_done.read(), ap_const_boolean_0))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<2>) ("XX");
            break;
    }
}

void block_aes_128::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"IV_V\" :  \"" << IV_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"key_V\" :  \"" << key_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"init\" :  \"" << init.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_return\" :  \"" << ap_return.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

